language: common-lisp

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/fast-http ~/lisp/fast-http
  - git clone https://github.com/fukamachi/quri ~/lisp/quri
  - git clone https://github.com/fukamachi/cl-cookie ~/lisp/cl-cookie
  - git clone https://github.com/fukamachi/dexador ~/lisp/dexador
  - git clone https://github.com/fukamachi/http-body ~/lisp/http-body
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -l prove -l cl-coveralls
       -e '(or (coveralls:with-coveralls ()
                 (every (function identity)
                        (list (prove:run :t-lack)
                              (prove:run :t-lack-middleware-static)
                              (prove:run :t-lack-middleware-session)
                              (prove:run :t-lack-middleware-csrf))))
               (uiop:quit -1))'
