language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=ecl
    - LISP=clisp

services:
  - redis-server

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - ros -e '(ql:update-all-dists :prompt nil)'
  - git clone https://github.com/fukamachi/clack ~/lisp/clack
  - git clone https://github.com/rpav/fast-io ~/lisp/fast-io
  - git clone https://github.com/Rudolph-Miller/jonathan ~/lisp/jonathan
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config

script:
  - if [ "$LISP" = "ecl" ] || [ "$LISP" = "clisp" ]; then
      ls t-*.asd | grep -v t-lack-session-store-dbi.asd | xargs run-prove;
    else
      run-prove t-*.asd;
    fi