language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh

before_script:
  - git clone https://github.com/fukamachi/clack ~/lisp/clack
  - git clone https://github.com/fukamachi/cl-coveralls $TRAVIS_BUILD_DIR/quicklisp/local-projects/cl-coveralls

script:
  - COVERAGE_EXCLUDE=t/ ./run-test.ros t-*.asd
