language: common-lisp

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/fast-http ~/lisp/fast-http
  - git clone https://github.com/fukamachi/quri ~/lisp/quri
  - git clone https://github.com/fukamachi/cl-cookie ~/lisp/cl-cookie
  - git clone https://github.com/fukamachi/dexador ~/lisp/dexador
  - git clone https://github.com/fukamachi/http-body ~/lisp/http-body
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -l prove -l cl-coveralls
       -e '(or (coveralls:with-coveralls
                 (loop for file in (uiop:directory-files (uiop:ensure-directory-pathname (uiop:getenv "TRAVIS_BUILD_DIR")))
                       when (and (string= (pathname-type file) "asd")
                                 (< 2 (length (pathname-name file)))
                                 (string= (pathname-name file) "t-" :end1 2))
                         collect (pathname-name file) into test-files
                       finally
                         (return (not (some (function null) (mapcar (function prove:run) test-files))))))
               (uiop:quit -1))'
