language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

before_script:
  - git clone https://github.com/fukamachi/dexador ~/lisp/dexador

script:
  - cl -l prove -e '(or (prove:run :t-lack) (uiop:quit -1))'
  - cl -l prove -e '(or (prove:run :t-lack-middleware-static) (uiop:quit -1))'
